services:
  db:
    image: postgres:14-alpine
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookstore_dev
    ports:
<<<<<<< HEAD
      - '5433:5432'
=======
      - '5432:5432'
>>>>>>> origin/master
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
<<<<<<< HEAD
  postgres_data:
=======
  postgres_data:
>>>>>>> origin/master
